### ISSUE TITLE
Add waypoints to aircraft for new objectives

### ISSUE THREAD

**Issue by MacMillan-M** [7Cav-DCS/Cavhold#12]
Need to update aircraft for waypoints to the new objectives.

**Comment by MacMillan-M** [comment]
Pending method to add waypoints to all player aircraft on side.

Supposedly can be done using MOOSE or MIST.

Logic behind it is:
`
For all aircraft on coalition BLUE (side 2):
        Waypoint.add(HOTEL)
        Waypoint add(India)
        Waypoint add(Maykop)
`

**Comment by pingoocoder** [comment]
Resolved in #43 43
