### ISSUE TITLE
Move airboss off default freq 305

### ISSUE THREAD

**Issue by MacMillan-M** [7Cav-DCS/Cavhold#4]
All hornet players can hear the Airboss, even when on Anapa. Move Airboss off default freq onto a new freq either ATC. Or Carrier ATC Freq.

**Comment by stagghost** [comment]
All units will have to be separated as well because units in groups will hear everything even when not on freq when a unit inside their group in interacting with airboss.

**Comment by MacMillan-M** [comment]
Tracking, all BLUFOR units should already be seperated. Will make sure on next passthrough.
